### ISSUE TITLE
R6S的ImmortalWrt固件装不了...

### ISSUE THREAD

**Issue by xiandu999-yu** [chenmozhijin/luci-app-turboacc#11]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency nft-fullcone for luci-app-turboacc
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-turboacc found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-turboacc.
========================================================================================
需要nft-fullcone，但软件包搜索到的是kmod-nft-fullcone（没有shortcut-fe，因为我弄不到）........

**Comment by chenmozhijin** [comment]
已经修了，见 948df4fde17ce4481e4c3f38fabc261bb37cb214 。

不过这个软件包一般来说还是随固件一起编译比较好，因为有许多依赖要打内核补丁。

当然immortalwrt已经内置了全锥型 NAT相关的源码与补丁，但没有shortcut-fe的。

luci-app-turboacc是根据你所安装的对应的依赖显示对应的功能的，没有shortcut-fe只会不显示开启它的勾选框。

你可以尝试添加为opkg添加```--force-depends```选项来无视失败的依赖。见[openwrt官方的opkg文档](https://openwrt.org/zh/docs/techref/opkg#%E9%80%89%E9%A1%B9)
