### ISSUE TITLE
能给个feeds.conf 里面的示例就好了。

### ISSUE THREAD

**Issue by wkii** [chenmozhijin/luci-app-turboacc#13]
我在想办法把那些指令写到feeds.conf中。
如果能有一个现成的，就舒服了。

**Comment by chenmozhijin** [comment]
feeds.conf 只能添加包吧，能替换包吗？

**Comment by Journalist-HK** [comment]
能用SDK编译然后安装到现有的系统上吗

**Comment by chenmozhijin** [comment]
> 能用SDK编译然后安装到现有的系统上吗

luci界面可以用SDK编译
不过如果是官方openwrt的话只有软件流量分载(Flow Offload)与BBR 拥塞控制算法可以用
