### ISSUE TITLE
支持硬件流量分载和无线HNAT吗？

### ISSUE THREAD

**Issue by hpx502766238** [chenmozhijin/luci-app-turboacc#16]
如题，Redmi Router Ax6s（mtk7622平台）想用。

**Comment by chenmozhijin** [comment]
硬件流量分载应该是可以的，MTK 无线硬件加速需要[Filogic 8x0](https://github.com/openwrt/openwrt/blob/4300bc668819a77226b6e8ea079d3067f216e7bb/target/linux/mediatek/image/filogic.mk#L356C23-L356C35)（[mt7915e的驱动](https://github.com/openwrt/openwrt/blob/4300bc668819a77226b6e8ea079d3067f216e7bb/package/kernel/mt76/Makefile#L234C1-L240C6)）。
我很不确定它们是否可用，因为这些功能我都没有试过并且也不太了解，还是保持[原来LEDE的代码](https://github.com/chenmozhijin/turboacc/blob/d0af2dd7363a8355a898738f08610ac7d00c5a8c/luci-app-turboacc/root/etc/init.d/turboacc#L40C1-L60C2)。
luci-app-turboacc只是一个开关，功能主要看openwrt固件与硬件是否支持。
