### ISSUE TITLE
可以重新加入DNS的开关吗

### ISSUE THREAD

**Issue by v8040** [chenmozhijin/luci-app-turboacc#17]
提个建议:turboacc作为一个便捷的开关集合,希望作者修改下原版的DNS开关,相比其他的dns插件dnsproxy支持的协议最全,但没有luci,用命令行控器比较麻烦,如果可以在这里直接控制dnsproxy就很方便

**Comment by chenmozhijin** [comment]
> 提个建议:turboacc作为一个便捷的开关集合,希望作者修改下原版的DNS开关,相比其他的dns插件dnsproxy支持的协议最全,但没有luci,用命令行控器比较麻烦,如果可以在这里直接控制dnsproxy就很方便

https://github.com/muink/luci-app-dnsproxy 不能用吗？

**Comment by v8040** [comment]
不好意思啊,对openwrt不太熟,找半天没找到,感谢提供地址,我去试试
