### ISSUE TITLE
添加 linux 6.6 支持

### ISSUE THREAD

**Issue by catsimple** [chenmozhijin/luci-app-turboacc#22]
[nft-fullcone](https://github.com/chenmozhijin/turboacc/tree/package/nft-fullcone)和https://github.com/chenmozhijin/turboacc/blob/package/hack-6.1/952-add-net-conntrack-events-support-multiple-registrant.patch
经过测试在linux 6.6内核上工作正常，相信openwrt主线的pr很快就合并了https://github.com/openwrt/openwrt/pull/14868
请尽快修改相关脚本以及hack6.6以适配openwrt master的内核更新
![image](https://github.com/chenmozhijin/turboacc/assets/23014926/42911381-909d-481d-915d-e926a01f9cc9)
![image](https://github.com/chenmozhijin/turboacc/assets/23014926/1bf120ff-08e5-4306-8d24-284aff7573d4)
![image](https://github.com/chenmozhijin/turboacc/assets/23014926/31997408-d9cc-45fe-8e70-cefa71642733)

**Comment by chenmozhijin** [comment]
支持了
