### ISSUE TITLE
手动添加openwrt失败，提示 ./package not found

### ISSUE THREAD

**Issue by lzwdavid** [chenmozhijin/luci-app-turboacc#23]
curl -ssl https://raw.githubusercontent.com/chenmozhijin/tu
rboacc/luci/add_turboacc.sh -o add_turboacc.sh && bash add_turboacc.sh
./package not found

求问如何解决？谢谢。

**Comment by lzwdavid** [comment]
补充：
OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.119.80898-65ef406
Kernel Version | 5.10.176

**Comment by chenmozhijin** [comment]
要在openwrt的源码目录中运行这行命令。

**Comment by lzwdavid** [comment]
> 要在openwrt的源码目录中运行这行命令。

感谢
我已经在./package 目录中试过了，仍然说 ./package not found.

**Comment by chenmozhijin** [comment]
是克隆了openwrt源码的存储库的那个目录。里面包含package 这个文件夹。就是git clone https://git.openwrt.org/openwrt/openwrt.git再cd openwrt的目录

**Comment by lzwdavid** [comment]
问过一圈，有人说 “[badcrazy 发表于 2024-4-8 12:13](https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&pid=20138174&ptid=8363121)
turboacc只能编译进固件，事后安装装不进去的”
