### ISSUE TITLE
在 RAX300M 上无法启用 fullcone nat

### ISSUE THREAD

**Issue by mengguyi** [chenmozhijin/luci-app-turboacc#31]
![image](https://github.com/user-attachments/assets/07671d6e-2e2d-4c5f-9652-476ecda378c3)
如上
```
# find /lib/modules/ | grep nft_fullcone.ko
/lib/modules/5.15.167/nft_fullcone.ko
# /etc/init.d/firewall restart
Section zerotier option 'reload' is not supported by fw4
Automatically including '/usr/share/nftables.d/table-post/20-miniupnpd.nft'
Automatically including '/usr/share/nftables.d/chain-post/dstnat/20-miniupnpd.nft'
Automatically including '/usr/share/nftables.d/chain-post/forward/20-miniupnpd.nft'
Automatically including '/usr/share/nftables.d/chain-post/srcnat/20-miniupnpd.nft'
Removed nat rules for zt interface zthnhnlbib!
Removed nat rules for zt interface ztukuuwoiq!
Added nat rules for zt interface zthnhnlbib!
Added nat rules for zt interface ztukuuwoiq!
# cat "/sys/module/nft_flow_offload/refcnt"
1
# cat "/proc/sys/net/ipv4/tcp_congestion_control"
bbr
# cat "/sys/module/nft_fullcone/refcnt"
0
```

**Comment by chenmozhijin** [comment]
运行`nft -c 'add table inet fw4-fullcone-test; add chain inet fw4-fullcone-test dstnat { type nat hook prerouting priority -100; policy accept; fullcone; }; add chain inet fw4-fullcone-test srcnat { type nat hook postrouting priority -100; policy accept; fullcone; }; '`看看

**Comment by mengguyi** [comment]
> 运行`nft -c 'add table inet fw4-fullcone-test; add chain inet fw4-fullcone-test dstnat { type nat hook prerouting priority -100; policy accept; fullcone; }; add chain inet fw4-fullcone-test srcnat { type nat hook postrouting priority -100; policy accept; fullcone; }; '`看看

经过我的瞎折腾后发现是因为我在官方的 openwrt 上面使用 sysupgrade 文件升级的导致了这个问题。重新刷了我编译了 turboacc 的 openwrt 就 ok 了

**Comment by mengguyi** [comment]
应该是 sysupgrade 不会去升级内核，而用uboot重刷就把内核也重刷了。问题解决
