### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by ZJJCKA** [chenmozhijin/luci-app-turboacc#32]
curl -sSL https://raw.githubusercontent.com/chenmozhijin/turboacc/luci/add_turboacc.sh -o add_turboacc.sh && bash add_turboacc.sh --no-sfe
curl -sSL https://raw.githubusercontent.com/chenmozhijin/turboacc/luci/add_turboacc.sh -o add_turboacc.sh && bash add_turboacc.sh

**Comment by chenmozhijin** [comment]
应该是你的网络不好
