### ISSUE TITLE
[openwrt/23.05]An error occurred while building Netfilter in the linux kernel

### ISSUE THREAD

**Issue by lushangkan** [chenmozhijin/luci-app-turboacc#7]
**System:** Windows11 WSL Ubuntu22.04
**Openwrt Version:** [Official Openwrt](https://github.com/openwrt/openwrt) / openwrt-23.05
**Building target:** ramips/mt7621/Xiaomi redmi AC2100
**Error log:** [log](https://github.com/openwrt/openwrt)
**Error log summary:**
```
Register multiple callbacks to ct events (NF_CONNTRACK_CHAIN_EVENTS) [N/y/?] (NEW) make[7]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[6]: *** [Makefile:628: syncconfig] Error 2
make[5]: *** [Makefile:748: include/config/auto.conf.cmd] Error 2

```
**Diffconfig:** [config](https://pastebin.com/DvVNcqMb)

**Comment by chenmozhijin** [comment]
If you don't need to compile sfe, please delete target/linux/generic/hack-5.15/953-net-patch-linux-kernel-to-support-shortcut-fe.patch

**Comment by lushangkan** [comment]
> 如果不需要编译sfe，请删除target/linux/generic/hack-5.15/953-net-patch-linux-kernel-to-support-shortcut-fe.patch

删除后仍然错误

**Comment by chenmozhijin** [comment]
[使用方法](https://github.com/chenmozhijin/turboacc/blob/luci/README.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)已[更新修复](https://github.com/chenmozhijin/turboacc/commit/fba2ae93e4cd75505c464f59d994730a19ccea5b)，并且通过了编译验证[Actions#39](https://github.com/chenmozhijin/turboacc/actions/runs/5587087678)，请尝试使用全新源码按照新的使用方法重新编译。
