### ISSUE TITLE
sfe加速在单线多播mwan3负载均衡做了端口转发情况下从外网访问跃点大的wan口下载数据会出现断流。

### ISSUE THREAD

**Issue by ghost** [chenmozhijin/luci-app-turboacc#9]
sfe加速在单线多播mwan3负载均衡做了端口转发情况下从外网访问跃点大的wan口下载数据会出现断流。

**Comment by chenmozhijin** [comment]
mwan3与sfe是互相冲突的
不过你可以参考一下：
https://github.com/coolsnowwolf/lede/issues/8958

https://www.right.com.cn/forum/thread-333361-5-1.html
这里提供了一个补丁你可以试一下。
希望可以帮到你。
